### ISSUE TITLE
More General Utilities With Representation Of Time In `idata` Objects

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [CDCgov/forecasttools-py#34]
TODO: Collect notes on time and `idata` objects. 

Watcher: @damonbayer

**Comment by damonbayer** [comment]
This functionality should

1. Allow for multiple variables to have their coordinates replaced with different dates at the same time.
2. The new coordinates should be derived by the user providing a start date and a time step.
3. If seems reasonable to you, I think we should only have to specify a dimension name. Then that dimension should have its coordinates changed in all groups where it exists.

**Comment by AFg6K7h4fhy2** [comment]
From elsewhere:

> I've been thinking about this:
> 
> > Allow for multiple variables to have their coordinates replaced with different dates at the same time.
>
> Multiple variables = "multiple idata groups"?
>
> and "different dates" is different `start_date_iso`s or intervals 1, 7, 14, etc...? Both should be supported, correct?

Reply:

> You could have some weekly Rt thing that starts on January 1 and a daily hospital admissions that start on February 1. You should be able to specify that.
